### ISSUE TITLE
Create FormKiQ One-Click Installs for Additional AWS Regions

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#117]
In order to provide a more global presence, it would be great to have one-click installs in the following AWS Regions:

us-west-2 (Oregon)
sa-east-1 (Sao Paulo)

It would be great to also support a region in Australia and East Asia:

ap-southeast-2 (Sydney)
ap-northeast-2 (Seoul)

All four should have support for all AWS services leveraged by FormKiQ, including Fargate, Cognito, and API Gateway.

**Comment by mfriesen** [comment]
Added us-west-2 & sa-east-1

**Comment by mfriesen** [comment]
added ap-southeast-2 & ap-northeast-2
