### ISSUE TITLE
add GET/PATCH /configs API endpoints

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-core#126]
Add API to allow the gettings / updating of Site Level configs via APIs 
GET /configs
PATCH /configs
{
"key":"","value":""
}

**Comment by reganwolfrom** [comment]
@mfriesen here are my RESTful recommendations:

Since there is only one resource, which is list of configuration settings, we should use the following endpoint URLs:
- GET /configuration
- PATCH /configuration
