### ISSUE TITLE
Add GET/POST/DELETE /configuration/apiKeys

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-core#128]
Allow the ability for the admin user to create API Keys to access the API.

**Comment by reganwolfrom** [comment]
Here are my recommendations for RESTful design:

- GET /configuration/apiKeys
- POST /configuration/apiKeys
- DELETE /configuration/apiKeys/{apiKey}

For POST /configuration/apiKeys, the assumption I've made from the API docs is that the `apiKey` is auto-generated, so we don't need to worry about validation, and the result will always be compatible as a REST Resource, i.e., no spaces or other punctuation or symbols.

For now, there is no GET /configuration/apiKeys/{apiKey}, but can be added as a future enhancement based on demand.
