### ISSUE TITLE
Support for updating multiple tags with one request.

### ISSUE THREAD

**Issue by Stason1o** [formkiq/formkiq-core#130]
Recently changes where introduced for POST /documents/{documentId}/tags, to support adding List of tags. 
I would like to suggest adding same support for updating multiple document tags in one request for 
PUT /documents/{documentId}/tags/{tagKey}

**Comment by RyanBuhrWA** [comment]
See if the `PATCH /documents/{documentId}` API will solve this for you. It allows you to send an array of tags to a document and add or update all of them. Here's the documentation for it: [Update Document API reference](https://docs.formkiq.com/docs/1.10.0/api/index.html#tag/Documents/operation/UpdateDocument)

**Comment by Stason1o** [comment]
@RyanBuhrWA , didn't see that functionality, was looking specifically on DocumentTags endpoints. I will try your suggestion today to see if it works fine for me and will come back with details later. Thanks!

**Comment by mfriesen** [comment]
@Stason1o We will add this to our roadmap.

**Comment by Stason1o** [comment]
So, follow up to workaround @RyanBuhrWA mentioned with patch endpoint. I tried to send a payload, having only list of tags supplied, without content, and then, all getDocumentContent requests are failing with 500, but I couldn't find logs for the root cause of this( limited access to company CloudWatch) so, I guess this does not fit my case(unless I get access to CW and investigate logs).
Supplying everytime content could be resource heavy, having in mind that documents could be huge size, and rewriting same content everytime tags are updated is also not a good solution..
But anyway, thanks for helping!

Will stick to current implementation - looping through tags and calling PUT document tag one by one, until new endpoint is released

**Comment by mfriesen** [comment]
@Stason1o Can you provide the request you sent using PATCH /documents/{documentId} and we can look into the 500 error you are seeing.

**Comment by Stason1o** [comment]
@mfriesen Hi,
So basically the steps I am performing with document:
1. Create document: POST: /documents with valid body - 200 Response
2. Update Document, 2 steps:
> Adding New tags( if they don't exist on document yet) using POST: /documents/{documentId}/tags
> Updating Existing ones, using PATCH: /documents/{documentId}, with payload and getting 200 Response:
```
{
"tags": [
 {
    "key": "string",
    "value":"string",
 },
 {
    "key2": "string",
    "value2":"string",
 }
]
```
I am not supplying content for this request, because I don't have it fetched at that moment from Formkiq. Sending content as a part of this request will require addiitional GetDocumentContent, which is "redundand" for me, because I am working with tags only at that moment.

3. Trying to get documentContent and this fails with 500 Response, indicating url, I was calling (could be our custom error response)

If I call GetDocumentContent before calling Patch Document, I receive 200 Response and document content. After calling Patch Document, and then GetDocumentContent - I get 500 response.
I suppose, that after calling Patch Document without supplying content in request body, FormKiq will set is as null? and this is causing issues on GetDocumentContent?

**Comment by mfriesen** [comment]
> Recently changes where introduced for POST /documents/{documentId}/tags, to support adding List of tags. I would like to suggest adding same support for updating multiple document tags in one request for PUT /documents/{documentId}/tags/{tagKey}

I assume you mean to add a PUT /documents/{documentId}/tags instead of /documents/{documentId}/tags/{tagKey}
with a body of
{
    "tags": [ ... ]
}

which would replace all the tags in a document?

**Comment by Stason1o** [comment]
@mfriesen, so basically I need an endpoint, which will accept body
{
"tags": []
}
and for each tag from request body, if this tag exists on document, its value will be updated to the value from request body.

Scenario:
1. I have created a document with tags:[ id, type(img), subtype(nature)]
2. I want to add additional tags to it. I use endpoint POST /documents/{documentId}/tags with body, 
containig new tags:
 { 
"tags": [case, comment, description, status(in_validation)] 
}. In result now document has list of tags:[id, type(img),  subtype(nature), case, comment, description, status]
3. Now I want to update some of the tags - type(png), subtype(city).
With current version, I need to use PUT/documents/{documentId}/tags/{tagKey} and make a call for each tag I want to update and supply new value/values
Feature request - have an endpoint which accepts tags:[] and updates exising tags with supplied value/values
like PUT/PATCH /documents/{documentId}/tags
{
tags:[type(png), subtype(city)]
}
so I will make one request for updating multiple tag values at once, instead of calling formkiq service 20-30 times, depending on how many tags I need to update

Result -  document tags are updated and document has tags:[id, type(png),  subtype(city), case, comment, description, status]

**Comment by mfriesen** [comment]
> GetDocumentContent - I get 500 response. I suppose, that after calling Patch Document without supplying content in request body, FormKiq will set is as null? and this is causing issues on GetDocumentContent?

@Stason1o 
Unfortunately I have been unable to duplicate the 500 issue you are experiencing. Would it be possible for you to look at the CloudWatch logs for the "DocumentsApi" lambda for a stack trace of the error you can send to me?

**Comment by Stason1o** [comment]
@mfriesen So, I tried this morning and got same results. 
Steps I performed:
1. Create a document with child document 
[addDocumentPayload.txt](https://github.com/formkiq/formkiq-core/files/11778600/addDocumentPayload.txt)

Note: At this point GET /documents/{documentId} and GET /documents/{documentId}/content are working as expected.

2. Update document tags, by calling update document endpoint PATCH /documents/{documentId}, by adding 4 new tags and 1 existing tag with body: { tags: [] }

[updateDocumentPayload.txt](https://github.com/formkiq/formkiq-core/files/11778602/updateDocumentPayload.txt)

Response is 200. 

3. Perform call to GET /documents/{documentId}/content
expected: 200 and content
actual - 500 error:

[logs.txt](https://github.com/formkiq/formkiq-core/files/11778603/logs.txt)

**Comment by mfriesen** [comment]
@Stason1o Thank you so much for the details. I'm still not able to replicate the issue.

Which version of FormKiQ are you using? From the logs, it looks like you are on v1.8.9?

**Comment by Stason1o** [comment]
@mfriesen Yeah, it's 1.8.X (not sure about minor version), we will be migrating to newer version as soon as v1.12 will be out =)
Anyway, thanks for help.
