### ISSUE TITLE
 graalvmNativeImage does not work under Windows

### ISSUE THREAD

**Issue by bmschwa** [formkiq/formkiq-core#132]
Please try building (`gradle build`) windows on at commit 23216ce6

... See thread at https://github.com/formkiq/formkiq-core/discussions/129#discussioncomment-6054456

**Comment by mfriesen** [comment]
@bmschwa I've updated the v1.11.0 branch and I've been able to build on a Windows machines. Version 1.11.0 introduced tesseract ocr, so you will need to install https://tesseract-ocr.github.io/tessdoc/Installation.html for the tests to pass.

**Comment by bmschwa** [comment]
I think that did it.  ytt is another non-standard windows dependency, but once I installed that - and waited an hr - it all seemed to come together,.

**Comment by mfriesen** [comment]
Yes, unfortunately graalvm's build performance under Windows isn't as good as it is under Linux. 

I'm glad it worked for you!
