### ISSUE TITLE
Updating one or more tags across multiple documents at once

### ISSUE THREAD

**Issue by RyanBuhrWA** [formkiq/formkiq-core#133]
We have a need to be able to update one tag across multiple documents all at once. One method would be to allow sending a list of document IDs in the body of a `POST` or `PATCH` along with the tag info we'd want them all to have. A more convenient method would allow for sending other tag criteria by which to identify all the documents that need the new or updated tag(s).
 Something like
```json
{
    "getDocumentsByTag": {
        "key": "category",
        "value": 47
    },
    "newOrUpdatedTags": [{
        "key": "authorName",
        "value": "Doe, John"
    }]
}
```
would result in all documents that have the `category` tag with a value of `47` receiving a new tag called `authorName` with value `"Doe, John"`, or if they already have the tag, its value would just be updated.

**Comment by mfriesen** [comment]
Adding new API

PATCH /documents/tags
{
    "match":
    {
        "tag":
        {
            "key": "category",
            "value": "47"
        }
    },
    "update":
    {
        "tags":
        [
            {
                "key": "authorName",
                "value": "Doe, John"
            }
        ]
    }
}

**Comment by RyanBuhrWA** [comment]
Awesome, thanks Mike!
