### ISSUE TITLE
Not able to install with latest AWS Sam Release

### ISSUE THREAD

**Issue by azilentech** [formkiq/formkiq-core#14]
Not able to create create AWS cloudformation stack with latest AWS SAM CLI release.
Somehow gave error for S3 bucket creation.
Tried with Linux and Mac versions.
Once I took earlier version - Feb 2021, it started to work.

**Comment by mfriesen** [comment]
Hi @azilentech, try version v1.3.0 you should have better luck with it.

**Comment by azilentech** [comment]
Sure.
May I know the process to upgrade from the previous version to the new version?

**Comment by mfriesen** [comment]
You can use the "sam deploy" command will update the existing installation.
