### ISSUE TITLE
GET documents/{id}/fulltext returns 400 when using Typesense

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#145]
Endpoint: ```/documents/a17d368c-3ffb-49d8-8d59-35ade13206b3/fulltext?siteId=default```

Expected Result:
- should return data sent to fulltext search (Typesense), as it does with OpenSearch

Actual Result:
- 400 error: ```{"message":"HTTP Host may not be empty"}```

**Comment by mfriesen** [comment]
add typesense support for 
GET /documents/{documentId}/fulltext
DELETE /documents/{documentId}/fulltext
PUT /documents/{documentId}/fulltext
PATCH /documents/{documentId}/fulltext
DELETE /documents/{documentId}/fulltext/tags/{tagKey}
DELETE /documents/{documentId}/fulltext/tags/{tagKey}/{tagValue}
