### ISSUE TITLE
DOCUMENTTAGGING action sometimes results in tag keys not matching requested text

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#147]
Depending on the response from the AI API (in this case OpenAI, i.e., engine chatGPT), the returned JSON keys to not always match.

Example:
Sometimes using "document type" as a requested tag results in "document_type", and other times as "document type", "documentType", or as "documenttype".

**Comment by mfriesen** [comment]
Fixed in 1.11.1
