### ISSUE TITLE
Add ONLYOFFICE Community Edition to core

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#181]
In order to add a no-charge view and edit option for MS Office files, it would be ideal to add ONLYOFFICE CE into Core.

It's not clear whether or not this should be optional vs. default; maybe it should be considered similarly to Typesense.

**Comment by mfriesen** [comment]
Onlyoffice can't be added to run in a container as the resources required is too large. It makes more sense to use Google Drive / Office 365 integration instead.
