### ISSUE TITLE
DELETE /documents/ID does not appear to work on LOCAL

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#186]
While the message receives a message of "{ID} object deleted}, document appears to still be listing in local DynamoDB.

`curl -X DELETE -H "Authorization: XXX" "http://localhost:8080/documents/f24a776c-16aa-48b7-9b46-835cbfa62bc1"
{"message":"'f24a776c-16aa-48b7-9b46-835cbfa62bc1' object deleted"}%  `

**Comment by mfriesen** [comment]
Fixed in image formkiq/api-server:1.13.0-SNAPSHOT-20231115
