### ISSUE TITLE
Dockerhub image does not support amd64

### ISSUE THREAD

**Issue by mingfang** [formkiq/formkiq-core#193]
https://hub.docker.com/r/formkiq/api-server/tags on contains `linux/arm64`

**Comment by reganwolfrom** [comment]
@mingfang We've now updated to include a linux/amd64 version: https://hub.docker.com/r/formkiq/api-server/tags

Please reply here if you try out and run into issues.

Thanks!

**Comment by mingfang** [comment]
@reganwolfrom Thanks for publishing the new image.  I can confirm it's working.  Closing issue.
