### ISSUE TITLE
DEEP LINKING: deepLinkPath property is using the deepest-level name as path and is not modifiable

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#217]
For deep links, using the deepest-level name may work in some cases, such as SharePoint (?), but for Google Drive, that name is an ID, rather than a human-readable name.

It isn't essential to retrieve a human-readable name, but ideally, it should be possible to provide a name for the 'path' property.

If it is not workable to do so, it may make sense to create a system attribute or property for this deepLinkName value, which could then be used for display when available.

**Comment by mfriesen** [comment]
@reganwolfrom Can you provide examples.

**Comment by reganwolfrom** [comment]
@mfriesen Here is an example:

```
{"deepLinkPath":"https://docs.google.com/document/d/1YZWn84REBdKPzlGbirnQOf7qneJgvmDweXWTQeT12O0","lastModifiedDate":"2024-02-29T14:54:01+0000","userId":"87ed86db-058a-4ebb-819a-63b3b36dd61e","path":"1YZWn84REBdKPzlGbirnQOf7qneJgvmDweXWTQeT12O0","insertedDate":"2023-12-15T22:19:40+0000","checksum":"d187f02890b4fcae7cf74d866dcb2d9b","siteId":"default","contentLength":2349320,"documentId":"b83e4b86-0bb3-4580-808e-77a06a01333b","contentType":"application/pdf"}
```

Ideally, this wouldn't show as a file named `1YZWn84REBdKPzlGbirnQOf7qneJgvmDweXWTQeT12O0`.

Also, the contentType is incorrect.

**Comment by reganwolfrom** [comment]
The plan is to allow path to be modifiable, allowing for file names.
