### ISSUE TITLE
PATCH /documents/{id} is not replacing specified metadata

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#24]
Observed with tags property.

Example:

```
PATCH /documents/{id}
{
  "tags": [
    {
      "key": "author",
      "value": "Bacon"
    }
  ]
}

```
An upload URL is returned (to allow document itself to be updated), but the metadata (at least not tags) is not updated.

**Comment by mfriesen** [comment]
fixed in 1.8.2
