### ISSUE TITLE
Site Schema: Add Document causes NullPointerException

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#275]
When creating a site schema with a required attribute and some optional ones, and then updating the schema to remove the required attribute or change it to optional, it seems that it's not possible to insert new documents without specifying the previously required attribute, even though it has been removed or changed to optional.

For example:
```
{
    "attributes": {
        "required": [
            {
                "attributeKey": "reqAttr"
            }
        ],
        "optional": [
            {
                "attributeKey": "optAttr"
            }
        ],
        "allowAdditionalAttributes": true
    },
    "name": "schema-test"
}
```
Then, we update the schema to:
```
{
    "attributes": {
        "optional": [
            {
                "attributeKey": "reqAttr"
            },
            {
                "attributeKey": "optAttr"
            }
        ],
        "allowAdditionalAttributes": true
    },
    "name": "schema-test"
}
```
or even:
```
{
    "attributes": {
        "optional": [
            {
                "attributeKey": "optAttr"
            }
        ],
        "allowAdditionalAttributes": true
    },
    "name": "schema-test"
}
```
Despite these updates, we still can't insert any new documents without the reqAttr attribute, which was previously required but is now either optional or removed.

**Comment by mfriesen** [comment]
Waiting for more examples, cannot replicate

**Comment by mfriesen** [comment]
If Schema's required fieldsis Nul
l{
  "name": "string",
  "attributes": {
    "required": null
  }
}

causes nullpointexception
