### ISSUE TITLE
Attempted rename of a document when path already exists provides 200 but loses document location (likely folder index)

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#303]
If a second document is uploaded with the same path, the document ID is appended to the path. But that does not prevent a user from renaming the document again using PATCH /documents/{id}.

When that happens, the response gives a 200, and the document disappears from POST /search, but the path itself isn't changed for the document.

It's possible that the operation updates on the folder index side but fails on the document update, hence the missing document, but this will need to be confirmed.

**Comment by mfriesen** [comment]
@reganwolfrom can you provide the API requests that demonstrate the issue.

**Comment by reganwolfrom** [comment]
@mfriesen it's the folder index that changes BEFORE the validation check on the document rename. So the document keeps its path with the UUID, but the folder index has already been changed, so the document gets "lost" in the index, and the index no longer matches the true path of the document.
