### ISSUE TITLE
500 Error in /search endpoint when using large "limit" with "responseFields"

### ISSUE THREAD

**Issue by RyanBuhrWA** [formkiq/formkiq-core#46]
I am able to reliably get results from the POST document search endpoint when providing a body parameter, but as soon as I add the "limit" query parameter, it returns with a 500 error.

Furthermore, the documentation says that the limit parameter has a default of "null", but the results are always limited to 10 in the absence of the limit query param.

**Comment by mfriesen** [comment]
When using a "limit" parameter in combination with a number of "responseFields" can end up with sending too many queries to DynamoDB. If the number of queries is > 100 they need to be split into batches
