### ISSUE TITLE
Add API endpoint to remove a document from one folder index and add to another

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#55]
As folders hold a list of documents within, moving a document from one folder to another would require an API call to remove the document from the source folder and add to the destination folder.

Example endpoint:

```POST /documents/{id}/move```
```{"sourceFolder": "Client ABC", "destinationFolder": "Client ABC/Client ABC Workspace"}```

NOTE: if we want to use `move` as the resource, we can also include `siteId` in future, allowing a move between folders, sites, or both, e.g., `sourceSiteId`

**Comment by mfriesen** [comment]
To keep the  document secondary indexing flexible my proposal would be to create an API under

POST /index/{indexType}/{operation}

So in this case there would be a 
POST /index/folder/move
{
	"source":"",
	"destination":""
}

This would allow other types of indexing to be created with relative ease.

**Comment by reganwolfrom** [comment]
@mfriesen after deleting documents (DELETE /documents/{id}), there is a list of "folders", one for each deleted document, returning on the root folder.

<img width="485" alt="Screen Shot 2022-10-25 at 12 39 26 PM" src="https://user-images.githubusercontent.com/19592350/197843943-b14b4933-728c-47bc-b5ac-1c2283fbcb55.png">

```
{
      "path": "Document List.xlsx",
      "folder": true,
      "tags": {
        
      }
    },
    {
      "path": "Financial Sample.xlsx",
      "folder": true,
      "tags": {
        
      }
    },
```

**Comment by reganwolfrom** [comment]
@mfriesen when moving from a folder to root, specifying "" as the target gives a 400:
```{"errors":[{"key":"target","error":"attribute is required"}]}```

But when providing "/" as the target, a new folder "/" is created in DynamoDB, and the document is moved to this folder.
<img width="657" alt="Screen Shot 2022-10-27 at 4 25 02 PM" src="https://user-images.githubusercontent.com/19592350/198401197-b456ce2c-ce28-4bbb-942a-53af1219168d.png">

Based on other concepts of root that we are using, i.e., the absence of a folder being no folder ("") instead of a root of "/", I think the blank target should be admissible. In addition, the "/" folder should not be created if "/" is provided as a destination.

Conversely, we can use "/" to signify root, and would also avoid creating the "/" folder.

**Comment by mfriesen** [comment]
Also need to support adding the same file multiple times to a folder

**Comment by mfriesen** [comment]
Sort Folders to the top

**Comment by mfriesen** [comment]
Tag meta data, see all tags in site

**Comment by mfriesen** [comment]
search box for path
