### ISSUE TITLE
GET /documents/{id}/upload overwrites file without creating a new version

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#87]
Steps to reproduce:

1. Upload a PDF file -> POST /documents/upload
2. Go to versions; expected result is to have only one version (current)
3. Click "Upload new PDF" and select a new version of the file -> GET /documents/{id}/upload
4. Document uploads but no new version is created, i.e., GET /documents/{id}/versions responds with empty array for documents

**Comment by mfriesen** [comment]
fixed
