### ISSUE TITLE
Cannot create tags with some siteIds (POST /documents/{id}/tags)

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#89]
When submitting a POST /documents/{id}/tags to 'default' or a site named with the user's email, I can create tags, but when sending the same type of request to an existing document in sites named 'New_York' and 'Chicago', I receive a 500.

These are read/write groups, not read-only groups.

**Comment by mfriesen** [comment]
moved to formkiq-module-fulltext module
