### ISSUE TITLE
Add more info on POST /search limitations in API spec

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#98]
It's not currently clear that POST /search supports either DynamoDB (i.e., tags, dateInserted) or Typesense (i.e., text) on a single request

**Comment by mfriesen** [comment]
Updated text to the following:

Document search query request;

Supports searching DynamoDB for document(s) by a single TAG key and/or value. Value can be "exacted" or "begins_with" matched. Search can be filtered to only check certain documentIds (up to 100 documentIds accepted).

If Typesense is enabled, full text search is supported through the "text" parameter. Full text search will look for the text in the "content" and/or document "meta data".

See requestBody examples below for commmon examples.

Added Typesense_Fulltext_Search example as well.
<img width="835" alt="Typesense_fulltext" src="https://github.com/formkiq/formkiq-core/assets/250329/9d08462b-95ab-4f08-b4ce-c3cf33164e42">

**Comment by mfriesen** [comment]
https://raw.githubusercontent.com/formkiq/formkiq-core/v1.13.0/docs/openapi/openapi-jwt.yaml

**Comment by reganwolfrom** [comment]
@mfriesen That looks good to me. Only issue is that your description has "meta data" instead of "metadata"; I think we're displaying as one word in other places.
